services:
  client:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./client:/app
    command: sh -c "npm ci && npm run dev -- --host"
    ports:
      - '3001:3001'
    environment:
      - VITE_API_BASE=http://localhost:7001
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:7.0
    ports:
      - '27017:27017'
    volumes:
      - battleship-db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo-express:
    image: mongo-express:1.0.0
    container_name: 'mongo-express'
    restart: always
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
    ports:
      - '8081:8081'
    depends_on:
      mongo:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 128m

  redis: # система кеширования
    container_name: 'pvsredis'
    image: 'redis:alpine'
    restart: always
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'redis-cli --no-auth-warning -a $$REDIS_PASSWORD ping | grep PONG',
        ]
      interval: 5s
      timeout: 3s
      start_period: 30s
      retries: 3
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - 6379:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - ./.env
    deploy:
      resources:
        limits:
          memory: 2G

volumes:
  battleship-db:
  redis-data:
