
services:
#  battleship-api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - '3000:3000'
#    depends_on:
#      - mongo
#      - postgres
#      - redis
#    environment:
#      - DATABASE_URL=mongodb://mongo:27017/battleship
#      - POSTGRES_HOST=postgres
#      - POSTGRES_PORT=5432
#      - REDIS_HOST=redis
#      - REDIS_PORT=6379

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - battleship-db:/data/db

  express:
    image: mongo-express
    container_name: "express"
    restart: always
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=user
      - ME_CONFIG_BASICAUTH_PASSWORD=sever321
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ADMINUSERNAME}
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ADMINPASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongo
    ports:
      - 8081:8081
    links:
      - mongo:mongo
    deploy:
      resources:
        limits:
          memory: 128m
    depends_on:
      - mongo

  postgres:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=battleship
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  redis:
    image: redis
    ports:
      - '6379:6379'

volumes:
  battleship-db:
  postgres-db:
